---
env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'standard-with-typescript'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:prettier/recommended'
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
plugins:
  - 'react'
  - 'react-hooks'
  - '@typescript-eslint'
  - 'prettier'
rules:
  camelcase: error
  no-duplicate-imports: error
  prettier/prettier: error
  quotes:
    - error
    - single
  react/react-in-jsx-scope: off
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  sort-imports: error
  spaced-comment: error
settings:
  import/resolver: typescript
  react:
    version: detect
